# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!

import psycopg2
import datetime

from PyQt5 import QtCore, QtGui, QtWidgets

from models.users.user import User
from models.users.user_data import UserData
from models.work.staff import Staff

class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(1280, 800)
        self.multi_widget = QtWidgets.QStackedWidget(main_window)
        self.multi_widget.setGeometry(QtCore.QRect(0, 0, 1280, 800))
        self.multi_widget.setStyleSheet("background-color: rgb(252, 252, 252);")
        self.multi_widget.setObjectName("multi_widget")
        self.login_page = QtWidgets.QWidget()
        self.login_page.setObjectName("login_page")
        self.zoo_name_text = QtWidgets.QLabel(self.login_page)
        self.zoo_name_text.setGeometry(QtCore.QRect(450, 40, 400, 100))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.zoo_name_text.setFont(font)
        self.zoo_name_text.setObjectName("zoo_name_text")
        self.login_button = QtWidgets.QPushButton(self.login_page)
        self.login_button.setGeometry(QtCore.QRect(500, 580, 280, 100))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.login_button.setFont(font)
        #self.login_button.clicked.connect(lambda: checkValidLogin(self.username_input.text(), self.pinput.text()))
        self.login_button.setStyleSheet("border-radius: 6;\n"
"background-color: rgb(232, 232, 232);\n"
"border-style: solid;\n"
"border-width: 1;\n"
"font: Roboto;\n"
"size: 30;")
        self.login_button.setObjectName("login_button")
        self.username_input = QtWidgets.QLineEdit(self.login_page)
        self.username_input.setGeometry(QtCore.QRect(490, 250, 300, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.username_input.setFont(font)
        self.username_input.setStyleSheet("border-radius: 6;\n"
"border-style: solid;\n"
"border-width: 1;\n"
"font: Roboto;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.username_input.setText("")
        self.username_input.setMaxLength(50)
        self.username_input.setObjectName("username_input")
        self.username_text = QtWidgets.QLabel(self.login_page)
        self.username_text.setGeometry(QtCore.QRect(290, 250, 180, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(26)
        self.username_text.setFont(font)
        self.username_text.setStyleSheet("background-color: rgb(252, 252, 252);")
        self.username_text.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.username_text.setObjectName("username_text")
        self.pin_text = QtWidgets.QLabel(self.login_page)
        self.pin_text.setGeometry(QtCore.QRect(290, 350, 180, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(26)
        self.pin_text.setFont(font)
        self.pin_text.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pin_text.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pin_text.setObjectName("pin_text")
        self.pinput = QtWidgets.QLineEdit(self.login_page)
        self.pinput.setGeometry(QtCore.QRect(490, 350, 300, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pinput.setFont(font)
        self.pinput.setStyleSheet("border-radius: 6;\n"
"background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1;\n"
"font: Roboto;\n"
"")
        self.pinput.setText("")
        self.pinput.setMaxLength(4)
        self.pinput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pinput.setObjectName("pinput")
        self.background_frame = QtWidgets.QFrame(self.login_page)
        self.background_frame.setGeometry(QtCore.QRect(0, 0, 1280, 800))
        self.background_frame.setStyleSheet("background-color: rgb(252, 252, 252);")
        self.background_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.background_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.background_frame.setObjectName("background_frame")
        self.background_frame.raise_()
        self.zoo_name_text.raise_()
        self.login_button.raise_()
        self.username_input.raise_()
        self.username_text.raise_()
        self.pin_text.raise_()
        self.pinput.raise_()
        self.multi_widget.addWidget(self.login_page)
        self.staff_schedule_page = QtWidgets.QWidget()
        self.staff_schedule_page.setObjectName("staff_schedule_page")
        self.sunday_schedule_listbox = QtWidgets.QListWidget(self.staff_schedule_page)
        self.sunday_schedule_listbox.setGeometry(QtCore.QRect(0, 210, 180, 240))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.sunday_schedule_listbox.setFont(font)
        self.sunday_schedule_listbox.setObjectName("sunday_schedule_listbox")
        self.sunday_schedule_text = QtWidgets.QLabel(self.staff_schedule_page)
        self.sunday_schedule_text.setEnabled(False)
        self.sunday_schedule_text.setGeometry(QtCore.QRect(40, 151, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(20)
        self.sunday_schedule_text.setFont(font)
        self.sunday_schedule_text.setStyleSheet("color: rgb(18, 18, 18);\n"
"")
        self.sunday_schedule_text.setTextFormat(QtCore.Qt.AutoText)
        self.sunday_schedule_text.setAlignment(QtCore.Qt.AlignCenter)
        self.sunday_schedule_text.setObjectName("sunday_schedule_text")
        self.sunday_schedule_date_input = QtWidgets.QLabel(self.staff_schedule_page)
        self.sunday_schedule_date_input.setEnabled(False)
        self.sunday_schedule_date_input.setGeometry(QtCore.QRect(40, 180, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.sunday_schedule_date_input.setFont(font)
        self.sunday_schedule_date_input.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sunday_schedule_date_input.setTextFormat(QtCore.Qt.AutoText)
        self.sunday_schedule_date_input.setAlignment(QtCore.Qt.AlignCenter)
        self.sunday_schedule_date_input.setObjectName("sunday_schedule_date_input")
        self.monday_schedule_date_input = QtWidgets.QLabel(self.staff_schedule_page)
        self.monday_schedule_date_input.setEnabled(False)
        self.monday_schedule_date_input.setGeometry(QtCore.QRect(220, 180, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.monday_schedule_date_input.setFont(font)
        self.monday_schedule_date_input.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.monday_schedule_date_input.setTextFormat(QtCore.Qt.AutoText)
        self.monday_schedule_date_input.setAlignment(QtCore.Qt.AlignCenter)
        self.monday_schedule_date_input.setObjectName("monday_schedule_date_input")
        self.monday_schedule_text = QtWidgets.QLabel(self.staff_schedule_page)
        self.monday_schedule_text.setEnabled(False)
        self.monday_schedule_text.setGeometry(QtCore.QRect(220, 151, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(20)
        self.monday_schedule_text.setFont(font)
        self.monday_schedule_text.setStyleSheet("color: rgb(18, 18, 18);")
        self.monday_schedule_text.setTextFormat(QtCore.Qt.AutoText)
        self.monday_schedule_text.setAlignment(QtCore.Qt.AlignCenter)
        self.monday_schedule_text.setObjectName("monday_schedule_text")
        self.header_frame = QtWidgets.QFrame(self.staff_schedule_page)
        self.header_frame.setGeometry(QtCore.QRect(0, 0, 1280, 100))
        self.header_frame.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.welcome_text = QtWidgets.QLabel(self.header_frame)
        self.welcome_text.setGeometry(QtCore.QRect(40, 30, 170, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(30)
        font.setBold(False)
        font.setWeight(50)
        self.welcome_text.setFont(font)
        self.welcome_text.setAutoFillBackground(False)
        self.welcome_text.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(45, 45, 45);")
        self.welcome_text.setObjectName("welcome_text")
        self.staff_name_input = QtWidgets.QLabel(self.header_frame)
        self.staff_name_input.setGeometry(QtCore.QRect(216, 30, 300, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(30)
        font.setBold(False)
        font.setWeight(50)
        self.staff_name_input.setFont(font)
        self.staff_name_input.setAutoFillBackground(False)
        self.staff_name_input.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(45, 45, 45);")
        self.staff_name_input.setObjectName("staff_name_input")
        self.sign_out_button = QtWidgets.QPushButton(self.header_frame)
        self.sign_out_button.setGeometry(QtCore.QRect(1068, 15, 172, 72))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.sign_out_button.setFont(font)
        self.sign_out_button.setStyleSheet("border-radius: 6;\n"
"background-color:rgb(99, 99, 99);\n"
"font: Roboto;\n"
"size: 30;\n"
"color: rgb(250, 250, 250);")
        self.sign_out_button.setObjectName("sign_out_button")
        self.clock_button = QtWidgets.QPushButton(self.header_frame)
        self.clock_button.setGeometry(QtCore.QRect(876, 15, 172, 72))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.clock_button.setFont(font)
        self.clock_button.setStyleSheet("border-radius: 6;\n"
"background-color:rgb(99, 99, 99);\n"
"font: Roboto;\n"
"size: 30;\n"
"color: rgb(250, 250, 250);")
        self.clock_button.setObjectName("clock_button")
        self.staff_name_input.raise_()
        self.welcome_text.raise_()
        self.sign_out_button.raise_()
        self.clock_button.raise_()
        self.schedule_header_frame = QtWidgets.QFrame(self.staff_schedule_page)
        self.schedule_header_frame.setGeometry(QtCore.QRect(0, 100, 1280, 50))
        self.schedule_header_frame.setStyleSheet("background-color: rgb(232, 232, 232);")
        self.schedule_header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.schedule_header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.schedule_header_frame.setObjectName("schedule_header_frame")
        self.schedule_text = QtWidgets.QLabel(self.schedule_header_frame)
        self.schedule_text.setGeometry(QtCore.QRect(20, 5, 250, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(24)
        self.schedule_text.setFont(font)
        self.schedule_text.setStyleSheet("background-color: rgb(232, 232, 232);")
        self.schedule_text.setObjectName("schedule_text")
        self.schedule_line = QtWidgets.QFrame(self.staff_schedule_page)
        self.schedule_line.setGeometry(QtCore.QRect(0, 150, 1280, 3))
        self.schedule_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.schedule_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.schedule_line.setObjectName("schedule_line")
        self.worked_header_frame = QtWidgets.QFrame(self.staff_schedule_page)
        self.worked_header_frame.setGeometry(QtCore.QRect(0, 450, 1280, 50))
        self.worked_header_frame.setStyleSheet("background-color: rgb(232, 232, 232);")
        self.worked_header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.worked_header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.worked_header_frame.setObjectName("worked_header_frame")
        self.time_worked_text = QtWidgets.QLabel(self.worked_header_frame)
        self.time_worked_text.setGeometry(QtCore.QRect(860, 5, 200, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(24)
        self.time_worked_text.setFont(font)
        self.time_worked_text.setStyleSheet("background-color: rgb(232, 232, 232);")
        self.time_worked_text.setObjectName("time_worked_text")
        self.clocked_time_text = QtWidgets.QLabel(self.worked_header_frame)
        self.clocked_time_text.setGeometry(QtCore.QRect(20, 5, 250, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(24)
        self.clocked_time_text.setFont(font)
        self.clocked_time_text.setStyleSheet("background-color: rgb(232, 232, 232);")
        self.clocked_time_text.setObjectName("clocked_time_text")
        self.hours_worked_input = QtWidgets.QLabel(self.worked_header_frame)
        self.hours_worked_input.setGeometry(QtCore.QRect(1064, 5, 90, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(24)
        self.hours_worked_input.setFont(font)
        self.hours_worked_input.setStyleSheet("background-color: rgb(232, 232, 232);")
        self.hours_worked_input.setObjectName("hours_worked_input")
        self.hours_worked_text = QtWidgets.QLabel(self.worked_header_frame)
        self.hours_worked_text.setGeometry(QtCore.QRect(1160, 5, 90, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(24)
        self.hours_worked_text.setFont(font)
        self.hours_worked_text.setStyleSheet("background-color: rgb(232, 232, 232);")
        self.hours_worked_text.setObjectName("hours_worked_text")
        self.monday_schedule_listbox = QtWidgets.QListWidget(self.staff_schedule_page)
        self.monday_schedule_listbox.setGeometry(QtCore.QRect(180, 210, 180, 240))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.monday_schedule_listbox.setFont(font)
        self.monday_schedule_listbox.setObjectName("monday_schedule_listbox")
        self.tuesday_schedule_listbox = QtWidgets.QListWidget(self.staff_schedule_page)
        self.tuesday_schedule_listbox.setGeometry(QtCore.QRect(360, 210, 180, 240))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.tuesday_schedule_listbox.setFont(font)
        self.tuesday_schedule_listbox.setObjectName("tuesday_schedule_listbox")
        self.wednesday_schedule_listbox = QtWidgets.QListWidget(self.staff_schedule_page)
        self.wednesday_schedule_listbox.setGeometry(QtCore.QRect(540, 210, 200, 240))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.wednesday_schedule_listbox.setFont(font)
        self.wednesday_schedule_listbox.setObjectName("wednesday_schedule_listbox")
        self.thurday_schedule_listbox = QtWidgets.QListWidget(self.staff_schedule_page)
        self.thurday_schedule_listbox.setGeometry(QtCore.QRect(740, 210, 180, 240))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.thurday_schedule_listbox.setFont(font)
        self.thurday_schedule_listbox.setObjectName("thurday_schedule_listbox")
        self.friday_schedule_listbox = QtWidgets.QListWidget(self.staff_schedule_page)
        self.friday_schedule_listbox.setGeometry(QtCore.QRect(920, 210, 180, 240))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.friday_schedule_listbox.setFont(font)
        self.friday_schedule_listbox.setObjectName("friday_schedule_listbox")
        self.saturday_schedule_listbox = QtWidgets.QListWidget(self.staff_schedule_page)
        self.saturday_schedule_listbox.setGeometry(QtCore.QRect(1100, 210, 180, 240))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.saturday_schedule_listbox.setFont(font)
        self.saturday_schedule_listbox.setObjectName("saturday_schedule_listbox")
        self.tuesday_schedule_text = QtWidgets.QLabel(self.staff_schedule_page)
        self.tuesday_schedule_text.setEnabled(False)
        self.tuesday_schedule_text.setGeometry(QtCore.QRect(400, 151, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(20)
        self.tuesday_schedule_text.setFont(font)
        self.tuesday_schedule_text.setAutoFillBackground(False)
        self.tuesday_schedule_text.setStyleSheet("color: rgb(18, 18, 18);")
        self.tuesday_schedule_text.setTextFormat(QtCore.Qt.AutoText)
        self.tuesday_schedule_text.setAlignment(QtCore.Qt.AlignCenter)
        self.tuesday_schedule_text.setObjectName("tuesday_schedule_text")
        self.tuesday_schedule_date_input = QtWidgets.QLabel(self.staff_schedule_page)
        self.tuesday_schedule_date_input.setEnabled(False)
        self.tuesday_schedule_date_input.setGeometry(QtCore.QRect(400, 180, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.tuesday_schedule_date_input.setFont(font)
        self.tuesday_schedule_date_input.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tuesday_schedule_date_input.setTextFormat(QtCore.Qt.AutoText)
        self.tuesday_schedule_date_input.setAlignment(QtCore.Qt.AlignCenter)
        self.tuesday_schedule_date_input.setObjectName("tuesday_schedule_date_input")
        self.wednesday_schedule_text = QtWidgets.QLabel(self.staff_schedule_page)
        self.wednesday_schedule_text.setEnabled(False)
        self.wednesday_schedule_text.setGeometry(QtCore.QRect(570, 151, 140, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(20)
        self.wednesday_schedule_text.setFont(font)
        self.wednesday_schedule_text.setAutoFillBackground(False)
        self.wednesday_schedule_text.setStyleSheet("color: rgb(18, 18, 18);")
        self.wednesday_schedule_text.setTextFormat(QtCore.Qt.AutoText)
        self.wednesday_schedule_text.setAlignment(QtCore.Qt.AlignCenter)
        self.wednesday_schedule_text.setObjectName("wednesday_schedule_text")
        self.wednesday_schedule_date_input = QtWidgets.QLabel(self.staff_schedule_page)
        self.wednesday_schedule_date_input.setEnabled(False)
        self.wednesday_schedule_date_input.setGeometry(QtCore.QRect(590, 180, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.wednesday_schedule_date_input.setFont(font)
        self.wednesday_schedule_date_input.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.wednesday_schedule_date_input.setTextFormat(QtCore.Qt.AutoText)
        self.wednesday_schedule_date_input.setAlignment(QtCore.Qt.AlignCenter)
        self.wednesday_schedule_date_input.setObjectName("wednesday_schedule_date_input")
        self.thursday_schedule_text = QtWidgets.QLabel(self.staff_schedule_page)
        self.thursday_schedule_text.setEnabled(False)
        self.thursday_schedule_text.setGeometry(QtCore.QRect(760, 151, 140, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(20)
        self.thursday_schedule_text.setFont(font)
        self.thursday_schedule_text.setAutoFillBackground(False)
        self.thursday_schedule_text.setStyleSheet("color: rgb(18, 18, 18);")
        self.thursday_schedule_text.setTextFormat(QtCore.Qt.AutoText)
        self.thursday_schedule_text.setAlignment(QtCore.Qt.AlignCenter)
        self.thursday_schedule_text.setObjectName("thursday_schedule_text")
        self.thursday_schedule_date_input = QtWidgets.QLabel(self.staff_schedule_page)
        self.thursday_schedule_date_input.setEnabled(False)
        self.thursday_schedule_date_input.setGeometry(QtCore.QRect(780, 180, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.thursday_schedule_date_input.setFont(font)
        self.thursday_schedule_date_input.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.thursday_schedule_date_input.setTextFormat(QtCore.Qt.AutoText)
        self.thursday_schedule_date_input.setAlignment(QtCore.Qt.AlignCenter)
        self.thursday_schedule_date_input.setObjectName("thursday_schedule_date_input")
        self.friday_schedule_text = QtWidgets.QLabel(self.staff_schedule_page)
        self.friday_schedule_text.setEnabled(False)
        self.friday_schedule_text.setGeometry(QtCore.QRect(940, 151, 140, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(20)
        self.friday_schedule_text.setFont(font)
        self.friday_schedule_text.setAutoFillBackground(False)
        self.friday_schedule_text.setStyleSheet("color: rgb(18, 18, 18);")
        self.friday_schedule_text.setTextFormat(QtCore.Qt.AutoText)
        self.friday_schedule_text.setAlignment(QtCore.Qt.AlignCenter)
        self.friday_schedule_text.setObjectName("friday_schedule_text")
        self.friday_schedule_date_input = QtWidgets.QLabel(self.staff_schedule_page)
        self.friday_schedule_date_input.setEnabled(False)
        self.friday_schedule_date_input.setGeometry(QtCore.QRect(960, 180, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.friday_schedule_date_input.setFont(font)
        self.friday_schedule_date_input.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.friday_schedule_date_input.setTextFormat(QtCore.Qt.AutoText)
        self.friday_schedule_date_input.setAlignment(QtCore.Qt.AlignCenter)
        self.friday_schedule_date_input.setObjectName("friday_schedule_date_input")
        self.saturday_schedule_date_input = QtWidgets.QLabel(self.staff_schedule_page)
        self.saturday_schedule_date_input.setEnabled(False)
        self.saturday_schedule_date_input.setGeometry(QtCore.QRect(1140, 179, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.saturday_schedule_date_input.setFont(font)
        self.saturday_schedule_date_input.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.saturday_schedule_date_input.setTextFormat(QtCore.Qt.AutoText)
        self.saturday_schedule_date_input.setAlignment(QtCore.Qt.AlignCenter)
        self.saturday_schedule_date_input.setObjectName("saturday_schedule_date_input")
        self.saturday_schedule_text = QtWidgets.QLabel(self.staff_schedule_page)
        self.saturday_schedule_text.setEnabled(False)
        self.saturday_schedule_text.setGeometry(QtCore.QRect(1120, 151, 140, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(20)
        self.saturday_schedule_text.setFont(font)
        self.saturday_schedule_text.setAutoFillBackground(False)
        self.saturday_schedule_text.setStyleSheet("color: rgb(18, 18, 18);")
        self.saturday_schedule_text.setTextFormat(QtCore.Qt.AutoText)
        self.saturday_schedule_text.setAlignment(QtCore.Qt.AlignCenter)
        self.saturday_schedule_text.setObjectName("saturday_schedule_text")
        self.wednesday_worked_listbox = QtWidgets.QListWidget(self.staff_schedule_page)
        self.wednesday_worked_listbox.setGeometry(QtCore.QRect(540, 560, 200, 240))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.wednesday_worked_listbox.setFont(font)
        self.wednesday_worked_listbox.setObjectName("wednesday_worked_listbox")
        self.friday_worked_date_input = QtWidgets.QLabel(self.staff_schedule_page)
        self.friday_worked_date_input.setEnabled(False)
        self.friday_worked_date_input.setGeometry(QtCore.QRect(960, 530, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.friday_worked_date_input.setFont(font)
        self.friday_worked_date_input.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.friday_worked_date_input.setTextFormat(QtCore.Qt.AutoText)
        self.friday_worked_date_input.setAlignment(QtCore.Qt.AlignCenter)
        self.friday_worked_date_input.setObjectName("friday_worked_date_input")
        self.sunday_worked_text = QtWidgets.QLabel(self.staff_schedule_page)
        self.sunday_worked_text.setEnabled(False)
        self.sunday_worked_text.setGeometry(QtCore.QRect(40, 501, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(20)
        self.sunday_worked_text.setFont(font)
        self.sunday_worked_text.setStyleSheet("color: rgb(18, 18, 18);\n"
"")
        self.sunday_worked_text.setTextFormat(QtCore.Qt.AutoText)
        self.sunday_worked_text.setAlignment(QtCore.Qt.AlignCenter)
        self.sunday_worked_text.setObjectName("sunday_worked_text")
        self.saturday_worked_listbox = QtWidgets.QListWidget(self.staff_schedule_page)
        self.saturday_worked_listbox.setGeometry(QtCore.QRect(1100, 560, 180, 240))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.saturday_worked_listbox.setFont(font)
        self.saturday_worked_listbox.setObjectName("saturday_worked_listbox")
        self.monday_worked_text = QtWidgets.QLabel(self.staff_schedule_page)
        self.monday_worked_text.setEnabled(False)
        self.monday_worked_text.setGeometry(QtCore.QRect(220, 501, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(20)
        self.monday_worked_text.setFont(font)
        self.monday_worked_text.setStyleSheet("color: rgb(18, 18, 18);")
        self.monday_worked_text.setTextFormat(QtCore.Qt.AutoText)
        self.monday_worked_text.setAlignment(QtCore.Qt.AlignCenter)
        self.monday_worked_text.setObjectName("monday_worked_text")
        self.tuesday_worked_text = QtWidgets.QLabel(self.staff_schedule_page)
        self.tuesday_worked_text.setEnabled(False)
        self.tuesday_worked_text.setGeometry(QtCore.QRect(400, 501, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(20)
        self.tuesday_worked_text.setFont(font)
        self.tuesday_worked_text.setAutoFillBackground(False)
        self.tuesday_worked_text.setStyleSheet("color: rgb(18, 18, 18);")
        self.tuesday_worked_text.setTextFormat(QtCore.Qt.AutoText)
        self.tuesday_worked_text.setAlignment(QtCore.Qt.AlignCenter)
        self.tuesday_worked_text.setObjectName("tuesday_worked_text")
        self.thursday_worked_listbox = QtWidgets.QListWidget(self.staff_schedule_page)
        self.thursday_worked_listbox.setGeometry(QtCore.QRect(740, 560, 180, 240))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.thursday_worked_listbox.setFont(font)
        self.thursday_worked_listbox.setObjectName("thursday_worked_listbox")
        self.saturday_worked_date_input = QtWidgets.QLabel(self.staff_schedule_page)
        self.saturday_worked_date_input.setEnabled(False)
        self.saturday_worked_date_input.setGeometry(QtCore.QRect(1140, 529, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.saturday_worked_date_input.setFont(font)
        self.saturday_worked_date_input.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.saturday_worked_date_input.setTextFormat(QtCore.Qt.AutoText)
        self.saturday_worked_date_input.setAlignment(QtCore.Qt.AlignCenter)
        self.saturday_worked_date_input.setObjectName("saturday_worked_date_input")
        self.friday_worked_listbox = QtWidgets.QListWidget(self.staff_schedule_page)
        self.friday_worked_listbox.setGeometry(QtCore.QRect(920, 560, 180, 240))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.friday_worked_listbox.setFont(font)
        self.friday_worked_listbox.setObjectName("friday_worked_listbox")
        self.wednesday_worked_date_input = QtWidgets.QLabel(self.staff_schedule_page)
        self.wednesday_worked_date_input.setEnabled(False)
        self.wednesday_worked_date_input.setGeometry(QtCore.QRect(590, 530, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.wednesday_worked_date_input.setFont(font)
        self.wednesday_worked_date_input.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.wednesday_worked_date_input.setTextFormat(QtCore.Qt.AutoText)
        self.wednesday_worked_date_input.setAlignment(QtCore.Qt.AlignCenter)
        self.wednesday_worked_date_input.setObjectName("wednesday_worked_date_input")
        self.monday_worked_listbox = QtWidgets.QListWidget(self.staff_schedule_page)
        self.monday_worked_listbox.setGeometry(QtCore.QRect(180, 560, 180, 240))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.monday_worked_listbox.setFont(font)
        self.monday_worked_listbox.setObjectName("monday_worked_listbox")
        self.tuesday_worked_listbox = QtWidgets.QListWidget(self.staff_schedule_page)
        self.tuesday_worked_listbox.setGeometry(QtCore.QRect(360, 560, 180, 240))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.tuesday_worked_listbox.setFont(font)
        self.tuesday_worked_listbox.setObjectName("tuesday_worked_listbox")
        self.sunday_worked_date_input = QtWidgets.QLabel(self.staff_schedule_page)
        self.sunday_worked_date_input.setEnabled(False)
        self.sunday_worked_date_input.setGeometry(QtCore.QRect(40, 530, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.sunday_worked_date_input.setFont(font)
        self.sunday_worked_date_input.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sunday_worked_date_input.setTextFormat(QtCore.Qt.AutoText)
        self.sunday_worked_date_input.setAlignment(QtCore.Qt.AlignCenter)
        self.sunday_worked_date_input.setObjectName("sunday_worked_date_input")
        self.thursday_worked_date_input = QtWidgets.QLabel(self.staff_schedule_page)
        self.thursday_worked_date_input.setEnabled(False)
        self.thursday_worked_date_input.setGeometry(QtCore.QRect(780, 530, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.thursday_worked_date_input.setFont(font)
        self.thursday_worked_date_input.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.thursday_worked_date_input.setTextFormat(QtCore.Qt.AutoText)
        self.thursday_worked_date_input.setAlignment(QtCore.Qt.AlignCenter)
        self.thursday_worked_date_input.setObjectName("thursday_worked_date_input")
        self.monday_worked_date_input = QtWidgets.QLabel(self.staff_schedule_page)
        self.monday_worked_date_input.setEnabled(False)
        self.monday_worked_date_input.setGeometry(QtCore.QRect(220, 530, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.monday_worked_date_input.setFont(font)
        self.monday_worked_date_input.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.monday_worked_date_input.setTextFormat(QtCore.Qt.AutoText)
        self.monday_worked_date_input.setAlignment(QtCore.Qt.AlignCenter)
        self.monday_worked_date_input.setObjectName("monday_worked_date_input")
        self.saturday_worked_text = QtWidgets.QLabel(self.staff_schedule_page)
        self.saturday_worked_text.setEnabled(False)
        self.saturday_worked_text.setGeometry(QtCore.QRect(1120, 501, 140, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(20)
        self.saturday_worked_text.setFont(font)
        self.saturday_worked_text.setAutoFillBackground(False)
        self.saturday_worked_text.setStyleSheet("color: rgb(18, 18, 18);")
        self.saturday_worked_text.setTextFormat(QtCore.Qt.AutoText)
        self.saturday_worked_text.setAlignment(QtCore.Qt.AlignCenter)
        self.saturday_worked_text.setObjectName("saturday_worked_text")
        self.thursday_worked_text = QtWidgets.QLabel(self.staff_schedule_page)
        self.thursday_worked_text.setEnabled(False)
        self.thursday_worked_text.setGeometry(QtCore.QRect(760, 501, 140, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(20)
        self.thursday_worked_text.setFont(font)
        self.thursday_worked_text.setAutoFillBackground(False)
        self.thursday_worked_text.setStyleSheet("color: rgb(18, 18, 18);")
        self.thursday_worked_text.setTextFormat(QtCore.Qt.AutoText)
        self.thursday_worked_text.setAlignment(QtCore.Qt.AlignCenter)
        self.thursday_worked_text.setObjectName("thursday_worked_text")
        self.sunday_worked_listbox = QtWidgets.QListWidget(self.staff_schedule_page)
        self.sunday_worked_listbox.setGeometry(QtCore.QRect(0, 560, 180, 240))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.sunday_worked_listbox.setFont(font)
        self.sunday_worked_listbox.setObjectName("sunday_worked_listbox")
        self.friday_worked_text = QtWidgets.QLabel(self.staff_schedule_page)
        self.friday_worked_text.setEnabled(False)
        self.friday_worked_text.setGeometry(QtCore.QRect(940, 501, 140, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(20)
        self.friday_worked_text.setFont(font)
        self.friday_worked_text.setAutoFillBackground(False)
        self.friday_worked_text.setStyleSheet("color: rgb(18, 18, 18);")
        self.friday_worked_text.setTextFormat(QtCore.Qt.AutoText)
        self.friday_worked_text.setAlignment(QtCore.Qt.AlignCenter)
        self.friday_worked_text.setObjectName("friday_worked_text")
        self.wednesday_worked_text = QtWidgets.QLabel(self.staff_schedule_page)
        self.wednesday_worked_text.setEnabled(False)
        self.wednesday_worked_text.setGeometry(QtCore.QRect(570, 501, 140, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(20)
        self.wednesday_worked_text.setFont(font)
        self.wednesday_worked_text.setAutoFillBackground(False)
        self.wednesday_worked_text.setStyleSheet("color: rgb(18, 18, 18);")
        self.wednesday_worked_text.setTextFormat(QtCore.Qt.AutoText)
        self.wednesday_worked_text.setAlignment(QtCore.Qt.AlignCenter)
        self.wednesday_worked_text.setObjectName("wednesday_worked_text")
        self.tuesday_worked_date_input = QtWidgets.QLabel(self.staff_schedule_page)
        self.tuesday_worked_date_input.setEnabled(False)
        self.tuesday_worked_date_input.setGeometry(QtCore.QRect(400, 530, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.tuesday_worked_date_input.setFont(font)
        self.tuesday_worked_date_input.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tuesday_worked_date_input.setTextFormat(QtCore.Qt.AutoText)
        self.tuesday_worked_date_input.setAlignment(QtCore.Qt.AlignCenter)
        self.tuesday_worked_date_input.setObjectName("tuesday_worked_date_input")
        self.worked_line = QtWidgets.QFrame(self.staff_schedule_page)
        self.worked_line.setGeometry(QtCore.QRect(0, 500, 1280, 3))
        self.worked_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.worked_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.worked_line.setObjectName("worked_line")
        self.worked_header_frame.raise_()
        self.schedule_header_frame.raise_()
        self.header_frame.raise_()
        self.sunday_schedule_listbox.raise_()
        self.sunday_schedule_text.raise_()
        self.sunday_schedule_date_input.raise_()
        self.monday_schedule_date_input.raise_()
        self.monday_schedule_text.raise_()
        self.schedule_line.raise_()
        self.monday_schedule_listbox.raise_()
        self.tuesday_schedule_listbox.raise_()
        self.wednesday_schedule_listbox.raise_()
        self.thurday_schedule_listbox.raise_()
        self.friday_schedule_listbox.raise_()
        self.saturday_schedule_listbox.raise_()
        self.tuesday_schedule_text.raise_()
        self.tuesday_schedule_date_input.raise_()
        self.wednesday_schedule_text.raise_()
        self.wednesday_schedule_date_input.raise_()
        self.thursday_schedule_text.raise_()
        self.thursday_schedule_date_input.raise_()
        self.friday_schedule_text.raise_()
        self.friday_schedule_date_input.raise_()
        self.saturday_schedule_date_input.raise_()
        self.saturday_schedule_text.raise_()
        self.wednesday_worked_listbox.raise_()
        self.friday_worked_date_input.raise_()
        self.sunday_worked_text.raise_()
        self.saturday_worked_listbox.raise_()
        self.monday_worked_text.raise_()
        self.tuesday_worked_text.raise_()
        self.thursday_worked_listbox.raise_()
        self.saturday_worked_date_input.raise_()
        self.friday_worked_listbox.raise_()
        self.wednesday_worked_date_input.raise_()
        self.monday_worked_listbox.raise_()
        self.tuesday_worked_listbox.raise_()
        self.sunday_worked_date_input.raise_()
        self.thursday_worked_date_input.raise_()
        self.monday_worked_date_input.raise_()
        self.saturday_worked_text.raise_()
        self.thursday_worked_text.raise_()
        self.sunday_worked_listbox.raise_()
        self.friday_worked_text.raise_()
        self.wednesday_worked_text.raise_()
        self.tuesday_worked_date_input.raise_()
        self.worked_line.raise_()
        self.multi_widget.addWidget(self.staff_schedule_page)
        self.admin_page = QtWidgets.QWidget()
        self.admin_page.setObjectName("admin_page")
        self.admin_header_frame = QtWidgets.QFrame(self.admin_page)
        self.admin_header_frame.setGeometry(QtCore.QRect(0, 0, 1280, 100))
        self.admin_header_frame.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.admin_header_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.admin_header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.admin_header_frame.setObjectName("admin_header_frame")
        self.admin_welcome_text = QtWidgets.QLabel(self.admin_header_frame)
        self.admin_welcome_text.setGeometry(QtCore.QRect(40, 30, 170, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(30)
        font.setBold(False)
        font.setWeight(50)
        self.admin_welcome_text.setFont(font)
        self.admin_welcome_text.setAutoFillBackground(False)
        self.admin_welcome_text.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(45, 45, 45);")
        self.admin_welcome_text.setObjectName("admin_welcome_text")
        self.admin_name_input = QtWidgets.QLabel(self.admin_header_frame)
        self.admin_name_input.setGeometry(QtCore.QRect(216, 30, 300, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(30)
        font.setBold(False)
        font.setWeight(50)
        self.admin_name_input.setFont(font)
        self.admin_name_input.setAutoFillBackground(False)
        self.admin_name_input.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(45, 45, 45);")
        self.admin_name_input.setObjectName("admin_name_input")
        self.admin_sign_out_button = QtWidgets.QPushButton(self.admin_header_frame)
        self.admin_sign_out_button.setGeometry(QtCore.QRect(1068, 15, 172, 72))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.admin_sign_out_button.setFont(font)
        self.admin_sign_out_button.setStyleSheet("border-radius: 6;\n"
"background-color:rgb(99, 99, 99);\n"
"font: Roboto;\n"
"size: 30;\n"
"color: rgb(250, 250, 250);")
        self.admin_sign_out_button.setObjectName("admin_sign_out_button")
        self.admin_home_button = QtWidgets.QPushButton(self.admin_header_frame)
        self.admin_home_button.setGeometry(QtCore.QRect(876, 15, 172, 72))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.admin_home_button.setFont(font)
        self.admin_home_button.setStyleSheet("border-radius: 6;\n"
"background-color:rgb(99, 99, 99);\n"
"font: Roboto;\n"
"size: 30;\n"
"color: rgb(250, 250, 250);")
        self.admin_home_button.setObjectName("admin_home_button")
        self.admin_stackedWidget = QtWidgets.QStackedWidget(self.admin_page)
        self.admin_stackedWidget.setGeometry(QtCore.QRect(0, 100, 1280, 700))
        self.admin_stackedWidget.setStyleSheet("background-color: rgb(252, 252, 252);")
        self.admin_stackedWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.admin_stackedWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.admin_stackedWidget.setObjectName("admin_stackedWidget")
        self.admin_stackedWidgetPage1 = QtWidgets.QWidget()
        self.admin_stackedWidgetPage1.setObjectName("admin_stackedWidgetPage1")
        self.admin_staff_button = QtWidgets.QPushButton(self.admin_stackedWidgetPage1)
        self.admin_staff_button.setGeometry(QtCore.QRect(80, 55, 520, 400))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.admin_staff_button.setFont(font)
        self.admin_staff_button.setStyleSheet("border-radius: 6;\n"
"background-color: rgb(232, 232, 232);\n"
"border-style: solid;\n"
"border-width: 1;\n"
"border-color: rgb(112, 112, 112);\n"
"font: Roboto;\n"
"size: 30;")
        self.admin_staff_button.setObjectName("admin_staff_button")
        self.admin_schedule_button = QtWidgets.QPushButton(self.admin_stackedWidgetPage1)
        self.admin_schedule_button.setGeometry(QtCore.QRect(680, 55, 520, 400))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.admin_schedule_button.setFont(font)
        self.admin_schedule_button.setStyleSheet("border-radius: 6;\n"
"background-color: rgb(232, 232, 232);\n"
"border-style: solid;\n"
"border-width: 1;\n"
"border-color: rgb(112, 112, 112);\n"
"font: Roboto;\n"
"size: 30;")
        self.admin_schedule_button.setObjectName("admin_schedule_button")
        self.admin_jobs_button = QtWidgets.QPushButton(self.admin_stackedWidgetPage1)
        self.admin_jobs_button.setGeometry(QtCore.QRect(80, 505, 320, 140))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.admin_jobs_button.setFont(font)
        self.admin_jobs_button.setStyleSheet("border-radius: 6;\n"
"background-color: rgb(232, 232, 232);\n"
"border-style: solid;\n"
"border-width: 1;\n"
"border-color: rgb(112, 112, 112);\n"
"font: Roboto;\n"
"size: 30;")
        self.admin_jobs_button.setObjectName("admin_jobs_button")
        self.admin_buildings_button = QtWidgets.QPushButton(self.admin_stackedWidgetPage1)
        self.admin_buildings_button.setGeometry(QtCore.QRect(480, 505, 320, 140))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.admin_buildings_button.setFont(font)
        self.admin_buildings_button.setStyleSheet("border-radius: 6;\n"
"background-color: rgb(232, 232, 232);\n"
"border-style: solid;\n"
"border-width: 1;\n"
"border-color: rgb(112, 112, 112);\n"
"font: Roboto;\n"
"size: 30;")
        self.admin_buildings_button.setObjectName("admin_buildings_button")
        self.admin_roles_button = QtWidgets.QPushButton(self.admin_stackedWidgetPage1)
        self.admin_roles_button.setGeometry(QtCore.QRect(880, 505, 320, 140))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.admin_roles_button.setFont(font)
        self.admin_roles_button.setStyleSheet("border-radius: 6;\n"
"background-color: rgb(232, 232, 232);\n"
"border-style: solid;\n"
"border-width: 1;\n"
"border-color: rgb(112, 112, 112);\n"
"font: Roboto;\n"
"size: 30;")
        self.admin_roles_button.setObjectName("admin_roles_button")
        self.admin_stackedWidget.addWidget(self.admin_stackedWidgetPage1)
        self.page = QtWidgets.QWidget()
        self.page.setStyleSheet("background-color: rgb(252, 252, 252);")
        self.page.setObjectName("page")
        self.admin_stackedWidget.addWidget(self.page)
        self.multi_widget.addWidget(self.admin_page)
########################################################################################################################
        self.login_button.clicked.connect(self.login_clicked)
        self.sign_out_button.clicked.connect(self.sign_out_clicked)
        self.admin_sign_out_button.clicked.connect(self.admin_sign_out_clicked)
########################################################################################################################
        self.retranslateUi(main_window)
        self.multi_widget.setCurrentIndex(0)
        self.admin_stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Form"))
        self.zoo_name_text.setText(_translate("main_window", "Team 16 Zoo"))
        self.login_button.setText(_translate("main_window", "Log In"))
        self.username_text.setText(_translate("main_window", "Username:"))
        self.pin_text.setText(_translate("main_window", "Pin:"))
        self.sunday_schedule_text.setText(_translate("main_window", "Sunday"))
        self.sunday_schedule_date_input.setText(_translate("main_window", "DA/TE/HERE"))
        self.monday_schedule_date_input.setText(_translate("main_window", "DA/TE/HERE"))
        self.monday_schedule_text.setText(_translate("main_window", "Monday"))
        self.welcome_text.setText(_translate("main_window", "Welcome"))
        self.staff_name_input.setText(_translate("main_window", "$Staff"))
        self.sign_out_button.setText(_translate("main_window", "Sign Out"))
        self.clock_button.setText(_translate("main_window", "Clock In"))
        self.schedule_text.setText(_translate("main_window", "Schedule"))
        self.time_worked_text.setText(_translate("main_window", "Time Worked:"))
        self.clocked_time_text.setText(_translate("main_window", "Clocked Time"))
        self.hours_worked_input.setText(_translate("main_window", "XX.XX"))
        self.hours_worked_text.setText(_translate("main_window", "Hours"))
        self.tuesday_schedule_text.setText(_translate("main_window", "Tuesday"))
        self.tuesday_schedule_date_input.setText(_translate("main_window", "DA/TE/HERE"))
        self.wednesday_schedule_text.setText(_translate("main_window", "Wednesday"))
        self.wednesday_schedule_date_input.setText(_translate("main_window", "DA/TE/HERE"))
        self.thursday_schedule_text.setText(_translate("main_window", "Thursday"))
        self.thursday_schedule_date_input.setText(_translate("main_window", "DA/TE/HERE"))
        self.friday_schedule_text.setText(_translate("main_window", "Friday"))
        self.friday_schedule_date_input.setText(_translate("main_window", "DA/TE/HERE"))
        self.saturday_schedule_date_input.setText(_translate("main_window", "DA/TE/HERE"))
        self.saturday_schedule_text.setText(_translate("main_window", "Saturday"))
        self.friday_worked_date_input.setText(_translate("main_window", "DA/TE/HERE"))
        self.sunday_worked_text.setText(_translate("main_window", "Sunday"))
        self.monday_worked_text.setText(_translate("main_window", "Monday"))
        self.tuesday_worked_text.setText(_translate("main_window", "Tuesday"))
        self.saturday_worked_date_input.setText(_translate("main_window", "DA/TE/HERE"))
        self.wednesday_worked_date_input.setText(_translate("main_window", "DA/TE/HERE"))
        self.sunday_worked_date_input.setText(_translate("main_window", "DA/TE/HERE"))
        self.thursday_worked_date_input.setText(_translate("main_window", "DA/TE/HERE"))
        self.monday_worked_date_input.setText(_translate("main_window", "DA/TE/HERE"))
        self.saturday_worked_text.setText(_translate("main_window", "Saturday"))
        self.thursday_worked_text.setText(_translate("main_window", "Thursday"))
        self.friday_worked_text.setText(_translate("main_window", "Friday"))
        self.wednesday_worked_text.setText(_translate("main_window", "Wednesday"))
        self.tuesday_worked_date_input.setText(_translate("main_window", "DA/TE/HERE"))
        self.admin_welcome_text.setText(_translate("main_window", "Welcome"))
        self.admin_name_input.setText(_translate("main_window", "$Admin"))
        self.admin_sign_out_button.setText(_translate("main_window", "Sign Out"))
        self.admin_home_button.setText(_translate("main_window", "Home"))
        self.admin_staff_button.setText(_translate("main_window", "Staff"))
        self.admin_schedule_button.setText(_translate("main_window", "Schedule"))
        self.admin_jobs_button.setText(_translate("main_window", "Jobs"))
        self.admin_buildings_button.setText(_translate("main_window", "Buildings"))
        self.admin_roles_button.setText(_translate("main_window", "Roles"))

    def login_clicked(self):
        # self.username_input.setText("LindseyM")
        # self.pinput.setText("1111")
        user = User.attempt_login(cur, self.username_input.text(), self.pinput.text())
        if (user != None):
                print('Signed in successfully!')
                if(user.user_type_id == 3):
                        self.multi_widget.setCurrentIndex(2) #set at end after work
                        self.admin_name_input.setText(self.get_staff_data(user).first_name)
                elif(user.user_type_id == 1): #Employees
                        self.multi_widget.setCurrentIndex(1)
                        self.staff_name_input.setText(self.get_staff_data(user).first_name)
                        self.initialize_schedule(user)
                else:
                        print("A user type error has occured!")
        else:
                print("invalid username or password entered.")
        self.clear_login()

    def get_staff_data(self, user):
        staff = Staff.get_staff_for_user(cur, user.id)
        return UserData.get_user_data(cur, staff.user_data_id)

    def clear_login(self):
        self.username_input.setText("")
        self.pinput.setText("")

    def clear_logout(self):
        self.monday_schedule_listbox.clear()
        self.monday_worked_listbox.clear()
        self.tuesday_schedule_listbox.clear()
        self.tuesday_worked_listbox.clear()
        self.wednesday_schedule_listbox.clear()
        self.wednesday_worked_listbox.clear()
        self.thurday_schedule_listbox.clear()
        self.thursday_worked_listbox.clear()
        self.friday_schedule_listbox.clear()
        self.friday_worked_listbox.clear()
        self.saturday_schedule_listbox.clear()
        self.saturday_worked_listbox.clear()
        self.sunday_schedule_listbox.clear()
        self.sunday_worked_listbox.clear()

    def sign_out_clicked(self):
        self.multi_widget.setCurrentIndex(0)
        self.clear_logout()

    def admin_sign_out_clicked(self):
        self.multi_widget.setCurrentIndex(0)

    def initialize_schedule(self, user):
            schedule = self.get_staff_schedule(user)
            schedule = self.get_current_shifts(schedule)
            self.populate_schedule(schedule)
            self.hours_worked(schedule)

    def get_staff_schedule(self, user):
        staff = Staff.get_staff_for_user(cur, user.id)
        return staff.get_shifts(cur)

    def populate_schedule(self, schedule):
        for shift in schedule:
                # print shift.date
                DOW = shift.date.weekday()
                #Used for populating the actual shifts they have on a given day
                if (DOW == 0):
                        monday_schedule = shift.start_time.strftime("%H:%M") + " - " + shift.end_time.strftime("%H:%M")
                        self.monday_schedule_listbox.addItem(monday_schedule)
                        monday_worked = shift.clock_in.strftime("%H:%M") + " - " + shift.clock_out.strftime("%H:%M")
                        self.monday_worked_listbox.addItem(monday_worked)
                elif (DOW == 1):
                        tuesday_schedule = shift.start_time.strftime("%H:%M") + " - " + shift.end_time.strftime("%H:%M")
                        self.tuesday_schedule_listbox.addItem(tuesday_schedule)
                        tuesday_worked = shift.clock_in.strftime("%H:%M") + " - " + shift.clock_out.strftime("%H:%M")
                        self.tuesday_worked_listbox.addItem(tuesday_worked)
                elif (DOW == 2):
                        wednesday_schedule = shift.start_time.strftime("%H:%M") + " - " + shift.end_time.strftime("%H:%M")
                        self.wednesday_schedule_listbox.addItem(wednesday_schedule)
                        wednesday_worked = shift.clock_in.strftime("%H:%M") + " - " + shift.clock_out.strftime("%H:%M")
                        self.wednesday_worked_listbox.addItem(wednesday_worked)
                elif (DOW == 3):
                        thursday_schedule = shift.start_time.strftime("%H:%M") + " - " + shift.end_time.strftime("%H:%M")
                        self.thurday_schedule_listbox.addItem(thursday_schedule)
                        thursday_worked = shift.clock_in.strftime("%H:%M") + " - " + shift.clock_out.strftime("%H:%M")
                        self.thursday_worked_listbox.addItem(thursday_worked)
                elif (DOW == 4):
                        friday_schedule = shift.start_time.strftime("%H:%M") + " - " + shift.end_time.strftime("%H:%M")
                        self.friday_schedule_listbox.addItem(friday_schedule)
                        friday_wroked = shift.clock_in.strftime("%H:%M") + " - " + shift.clock_out.strftime("%H:%M")
                        self.friday_worked_listbox.addItem(friday_wroked)
                elif (DOW == 5):
                        saturday_schedule = shift.start_time.strftime("%H:%M") + " - " + shift.end_time.strftime("%H:%M")
                        self.saturday_schedule_listbox.addItem(saturday_schedule)
                        saturday_worked = shift.clock_in.strftime("%H:%M") + " - " + shift.clock_out.strftime("%H:%M")
                        self.saturday_worked_listbox.addItem(saturday_worked)
                elif (DOW == 6):
                        sunday_schedule = shift.start_time.strftime("%H:%M") + " - " + shift.end_time.strftime("%H:%M")
                        self.sunday_schedule_listbox.addItem(sunday_schedule)
                        sunday_worked = shift.clock_in.strftime("%H:%M") + " - " + shift.clock_out.strftime("%H:%M")
                        self.sunday_worked_listbox.addItem(sunday_worked)

    def hours_worked(self, schedule):
            hours = 0
            minutes = 0
            for shift in schedule:
                    hours += int(shift.clock_out.strftime("%H")) - int(shift.clock_in.strftime("%H"))
                    minutes += 60 - int(shift.clock_out.strftime("%M"))
                    minutes += int(shift.clock_in.strftime("%M"))
            hours += minutes/60
            minutes %= 60
            minutes_of_hour = float(minutes)/0.6
            self.hours_worked_input.setText(str(hours) + "." + str(int(minutes_of_hour)))

    def get_current_shifts(self,schedule):
        current_year, current_week, current_DOW = datetime.date.today().isocalendar()
        current_shifts = []
        for shift in schedule:
                date_data = shift.date
                Year,WeekNum,DOW = date_data.isocalendar()
                if (WeekNum == current_week):
                        current_shifts.append(shift)

        current_day = datetime.date.today().strftime("%d")
        current_month = datetime.date.today().strftime("%m")
        sun_day = int(current_day) - int(DOW) - 0
        mon_day = int(current_day) - int(DOW) + 1
        tues_day = int(current_day) - int(DOW) + 2
        wednes_day = int(current_day) - int(DOW) + 3
        thurs_day = int(current_day) - int(DOW) + 4
        fri_day = int(current_day) - int(DOW) + 5
        satur_day = int(current_day) - int(DOW) + 6

        # date = month/day/year
        # set schedule date
        # set worked date
        sun_date = str(current_month) + "/" + str(sun_day) + "/" + str(current_year)
        self.sunday_schedule_date_input.setText(sun_date)
        self.sunday_worked_date_input.setText(sun_date)
        mon_date = str(current_month) + "/" + str(mon_day) + "/" + str(current_year)
        self.monday_schedule_date_input.setText(mon_date)
        self.monday_worked_date_input.setText(mon_date)
        tues_date = str(current_month) + "/" + str(tues_day) + "/" + str(current_year)
        self.tuesday_schedule_date_input.setText(tues_date)
        self.tuesday_worked_date_input.setText(tues_date)
        wednes_date = str(current_month) + "/" + str(wednes_day) + "/" + str(current_year)
        self.wednesday_schedule_date_input.setText(wednes_date)
        self.wednesday_worked_date_input.setText(wednes_date)
        thurs_date = str(current_month) + "/" + str(thurs_day) + "/" + str(current_year)
        self.thursday_schedule_date_input.setText(thurs_date)
        self.thursday_worked_date_input.setText(thurs_date)
        fri_date = str(current_month) + "/" + str(fri_day) + "/" + str(current_year)
        self.friday_schedule_date_input.setText(fri_date)
        self.friday_worked_date_input.setText(fri_date)
        satur_date = str(current_month) + "/" + str(satur_day) + "/" + str(current_year)
        self.saturday_schedule_date_input.setText(satur_date)
        self.saturday_worked_date_input.setText(satur_date)
        return  current_shifts

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.QWidget()
    ui = Ui_main_window()
    ui.setupUi(main_window)
    main_window.show()

    conn = psycopg2.connect(host="localhost", database="postgres", user="postgres", password="Troll321")
    conn.set_session(deferrable=True)
    cur = conn.cursor()

    sys.exit(app.exec_())
